#!/bin/bash
#echo "Starting SO-Fi!"
#sudo gnome-terminal -e "So-Fi_c/hostapd/hostapd So-Fi_c/hostapd/hostapd.conf"&
#sudo python So-Fi-demo/sofi_listener.py
#tail -f So-Fi-demo/myapp.log
echo "Shutting down!!"
sudo killall hostapd
sudo killall python
sudo killall dnsmasq
